### ISSUE TITLE
[Enhancement] "From" address in response draft editor automatically selects incorrect address.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/WebClients#382]
#### **Prerequisites**

1.	[x] I have searched open and closed issues for duplicates
1.	[ ] This isn't a feature request
1.	[ ] This is not a report about my app not working as expected

#### **Issue**

As https://github.com/anonaddy/anonaddy/discussions/613#discussioncomment-8773641 explains, when I am sent a message from an external service which modifies the From address to be a variant of an existent ProtonMail alias of mine, the response form automatically selects that alias:

> ![image](https://github.com/ProtonMail/WebClients/assets/42837531/e099e42a-eb7e-4719-b485-38d79c2ade70)

I want to be able to control whether it does this — sometimes it's desirable, other times not. How can this be overridden? It's somewhat of a security concern in retrospect.

#### Tasks

1. [ ] File this as a suggestion at [`protonmail.uservoice.com/#suggestion_title`][FRs].

   [FRs]: https://protonmail.uservoice.com/forums/945460-general-ideas/filters/my_feedback#suggestion_title

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/382#issue-2184122998

@RokeJulianLockhart, although in theory being able to choose the behaviour wouldn't be a bad thing, I've no need for this anymore, because its default behaviour works better.
