### ISSUE TITLE
[Enhancement] Adhere to `color-scheme: light dark`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/WebClients#384]
#### **Prerequisites**

1.	[x] I have searched open and closed issues for duplicates
1.	[ ] This isn't a feature request
1.	[ ] This is not a report about my app not working as expected

#### **Issue**

Like https://github.com/ProtonMail/proton-mail/issues/71#issue-905205233 describes, Proton Mail should switch themes depending upon the system-reported theme. https://protonmail.uservoice.com/forums/284483-proton-mail/suggestions/43402152-use-system-setting-for-light-dark-mode requests this, and has been erroneously closed as implemented.

#### Tasks

1. [ ] File this as a suggestion at [`protonmail.uservoice.com/#suggestion_title`][FRs].

   [FRs]: https://protonmail.uservoice.com/forums/945460-general-ideas/filters/my_feedback#suggestion_title

1. [ ] Wait for [`protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528`][bugs] to be implemented, so that this can be filed as a bug via the correct avenue.

   [bugs]: https://protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528-provide-public-bug-trackers-for-all-projects

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/384#issue-2200258196

Amazingly, I just... didn't see the feature at https://account.proton.me/u/1/mail/appearance#theme. 6 times. I suppose the human brain just shows what it wants to, sometimes.

**Comment by avidseeker** [comment]
This might be a regression. Protonmail doesn't detect system theme on Chromium.

* Chromium > Settings > Dark theme
* Check for `Sec-CH-Prefers-Color-Scheme: dark` http header in https://deviceinfo.me
* Protonmail > Settings > Theme > Sync with system
* Expected: display site in dark theme
* Result: site displayed in light theme

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/384#issuecomment-2194604172

@avidseeker, as aforexplained in https://github.com/ProtonMail/WebClients/issues/384#issuecomment-2012369317, this was merely a case of my own stupidity, especially since I'm using https://koji.fedoraproject.org/koji/rpminfo?rpmID=39016950 (so not Chromium).

Consequently, should you have identified an issue about the same problem but caused by a different cause (as it appears you have) I suggest that you file it separately at https://github.com/ProtonMail/WebClients/issues/new?assignees=&labels=&projects=&template=ask-a-question.md&title= (with the template modified as I have) because the content of this thread might become confusing otherwise to the poor triage owner or developer assigned.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/384#issuecomment-2194648886

@avidseeker, did you file another report for yourself?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/WebClients/issues/384#issuecomment-2463174779

Ah, located it: https://github.com/ProtonMail/WebClients/issues/396#issue-2378122178. Apologies.
