### ISSUE TITLE
[Task] Release the source markup for the documentation.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/WebClients#386]
#### **Prerequisites**

1.	[x] I have searched open and closed issues for duplicates
1.	[ ] This isn't a feature request
1.	[x] This is not a report about my app not working as expected

#### **Issue**

https://github.com/MicrosoftDocs does it - see https://github.com/MicrosoftDocs/PowerShell-Docs/tree/d5c11fe31a5032e79108d57af3ceaa2ac6c7d408 - it allows me to refer to specific versions using the commit. You should, too.

#### Tasks

1. [ ] File this as a suggestion at [`protonmail.uservoice.com/#suggestion_title`][FRs].

   [FRs]: https://protonmail.uservoice.com/forums/945460-general-ideas/filters/my_feedback#suggestion_title
