### ISSUE TITLE
[Enhancement] Don't override the browser font.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/WebClients#393]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [ ] This isn't a feature request
-   [ ] This is not a report about my app not working as expected

---

I'm using https://kojipkgs.fedoraproject.org//packages/firefox/127.0/1.fc40/x86_64/firefox-127.0-1.fc40.x86_64.rpm (from https://koji.fedoraproject.org/koji/rpminfo?rpmID=38850613) with `browser.display.use_document_fonts` set as `1` in `about:config`, which means that font preferences are respected. I'm forced to use this because `browser.display.use_document_fonts.icon_font_allowlist`:

> Material Icons, Material Icons Extended, Material Icons Outlined, Material Icons Round, Material Icons Sharp, Material Icons Two Tone, Google Material Icons, Material Symbols Outlined, Material Symbols Round, Material Symbols Rounded, Material Symbols Sharp

...isn't comprehensive enough, even for iconography at https://www.google.com/search. Consequently, please do not override the browser font. There's no reason to. I have `font.name.sans-serif.x-western` set to `monospace`, so ProtonMail appears very out-of-place.

#### Tasks

1. [ ] File this as a suggestion at [`protonmail.uservoice.com/#suggestion_title`][FRs].

   [FRs]: https://protonmail.uservoice.com/forums/945460-general-ideas/filters/my_feedback#suggestion_title

1. [ ] Wait for [`protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528`][bugs] to be implemented, so that this can be filed as a bug via the correct avenue.

   [bugs]: https://protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528-provide-public-bug-trackers-for-all-projects
