### ISSUE TITLE
[Bug] Not all members of the `text/` Media Type category render in the Mail previewer.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/WebClients#416]
> We are happy to answer your questions about the code or discuss technical ideas.

Please complete the following checklist (by adding [x]):

-   [x] I have searched open and closed issues for duplicates
-   [ ] This isn't a feature request
-   [ ] This is not a report about my app not working as expected

---

The Mail web client doesn't render all plain text attachment files in the previewer. As an example, despite `.eml` being of the `text/` Media Type category, it is considered to be “unsupported”, whereas `.HTML` is supported, and renders as plain text.

#### Tasks

1. [ ] File this as a suggestion at [`protonmail.uservoice.com/#suggestion_title`][FRs].

   [FRs]: https://protonmail.uservoice.com/forums/945460-general-ideas/filters/my_feedback#suggestion_title

1. [ ] Wait for [`protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528`][bugs] to be implemented, so that this can be filed as a bug via the correct avenue.

   [bugs]: https://protonmail.uservoice.com/forums/945460-general-ideas/suggestions/50436528-provide-public-bug-trackers-for-all-projects
